# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02c59f0bf6081eceee2eb3c863c3b0c2b98ded0a3d11aa5d1fd41bce281d248d510c209d1cbd07ccd9b2c29316fe40289ca9f2e7be6e491d6ce3bdbf93d84302

test:
  secret_key_base: 51fb848764c6dd5dd4d642f0ea1505f4c785e7d79fd034e29d533fab17e7edd76851f48fd932bf0ccd5b9e55d1dd09690bb8f91f126bac8981d4645c9c8499dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
